// <auto-generated />
namespace Playground.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class externaluseridchange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(externaluseridchange));
        
        string IMigrationMetadata.Id
        {
            get { return "201402041019325_external user id change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
