// <auto-generated />
namespace Playground.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class GameCategoryValidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GameCategoryValidation));
        
        string IMigrationMetadata.Id
        {
            get { return "201401151307174_GameCategoryValidation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
