// <auto-generated />
namespace Playground.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PlayersPerTeam : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PlayersPerTeam));
        
        string IMigrationMetadata.Id
        {
            get { return "201401142052488_PlayersPerTeam"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
